### ISSUE TITLE
[Tabs] 页签支持横向滚动

### ISSUE THREAD

**Issue by murisans** [kingdee/kdesign#801]
内容溢出滚动 + 滚动条隐藏实现
```css
.kd-tabs-tab-wrap {
      overflow: scroll;
      scrollbar-width: none;
      -ms-overflow-style:none;
}

.kd-tabs-tab-wrap::-webkit-scrollbar {
      display: none;
}

```

效果演示
![May-23-2024 21-18-11](https://github.com/kingdee/kdesign/assets/57647858/e09f5777-a92b-4055-a4ac-bf6688ff45c7)
